# Generated by Django 6.0.3 on 2026-04-04 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date et heure de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text="Indique si l'objet est actif (soft delete)")),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], default='PENDING', help_text="État de l'analyse", max_length=20)),
                ('title', models.CharField(blank=True, default='', help_text="Titre/description de l'analyse", max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Description détaillée')),
                ('started_at', models.DateTimeField(blank=True, help_text='Quand le traitement a commencé', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text="Quand le traitement s'est terminé", null=True)),
                ('task_id', models.CharField(blank=True, help_text='ID de la task Celery', max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analysis',
                'verbose_name_plural': 'Analyses',
                'db_table': 'analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date et heure de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text="Indique si l'objet est actif (soft delete)")),
                ('frames_analyzed', models.IntegerField(default=0, help_text='Nombre de frames analysées (pour vidéos)')),
                ('faces_detected', models.IntegerField(default=0, help_text='Nombre de visages détectés')),
                ('artifacts', models.JSONField(blank=True, default=list, help_text='Artefacts détectés')),
                ('processing_models', models.JSONField(blank=True, default=dict, help_text='Modèles utilisés et leurs scores')),
                ('analysis', models.OneToOneField(help_text="L'analyse associée", on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='analysis.analysis')),
            ],
            options={
                'verbose_name': 'Analysis Detail',
                'verbose_name_plural': 'Analysis Details',
                'db_table': 'analysis_details',
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date et heure de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text="Indique si l'objet est actif (soft delete)")),
                ('verdict', models.CharField(choices=[('AUTHENTIC', 'AUTHENTIC'), ('FAKE', 'FAKE'), ('SUSPICIOUS', 'SUSPICIOUS')], help_text='Verdict final', max_length=20)),
                ('confidence_score', models.FloatField(help_text='Score de confiance (0.0 à 1.0)')),
                ('authenticity_score', models.FloatField(help_text="Score d'authenticité (0.0 à 1.0)")),
                ('deepfake_score', models.FloatField(help_text='Score de deepfake (0.0 à 1.0)')),
                ('confidence_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Détails supplémentaires (JSON)')),
                ('report', models.TextField(blank=True, default='', help_text='Rapport détaillé en texte')),
                ('recommendations', models.TextField(blank=True, default='', help_text='Recommandations')),
                ('analysis', models.OneToOneField(help_text="L'analyse associée", on_delete=django.db.models.deletion.CASCADE, related_name='result', to='analysis.analysis')),
            ],
            options={
                'verbose_name': 'Analysis Result',
                'verbose_name_plural': 'Analysis Results',
                'db_table': 'analysis_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date et heure de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text="Indique si l'objet est actif (soft delete)")),
                ('file', models.FileField(help_text='Le fichier uploadé', upload_to='uploads/medias/%Y/%m/%d/')),
                ('filename', models.CharField(help_text='Nom du fichier original', max_length=255)),
                ('media_type', models.CharField(choices=[('image', 'IMAGE'), ('video', 'VIDEO'), ('audio', 'AUDIO')], help_text='Type de média', max_length=20)),
                ('file_size', models.BigIntegerField(help_text='Taille en bytes')),
                ('file_extension', models.CharField(help_text='Extension du fichier', max_length=10)),
                ('mime_type', models.CharField(help_text='MIME type', max_length=50)),
                ('width', models.IntegerField(blank=True, help_text='Largeur en pixels', null=True)),
                ('height', models.IntegerField(blank=True, help_text='Hauteur en pixels', null=True)),
                ('duration', models.FloatField(blank=True, help_text='Durée en secondes (pour vidéos/audio)', null=True)),
                ('user', models.ForeignKey(help_text="L'utilisateur qui a uploadé", on_delete=django.db.models.deletion.CASCADE, related_name='medias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Medias',
                'db_table': 'medias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='analysis',
            name='media',
            field=models.ForeignKey(help_text='Le fichier à analyser', on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='analysis.media'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['user', '-created_at'], name='medias_user_id_ca6d3b_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['media_type'], name='medias_media_t_452285_idx'),
        ),
        migrations.AddIndex(
            model_name='analysis',
            index=models.Index(fields=['user', '-created_at'], name='analyses_user_id_0211ba_idx'),
        ),
        migrations.AddIndex(
            model_name='analysis',
            index=models.Index(fields=['status'], name='analyses_status_a2cfc9_idx'),
        ),
    ]
